# Generated by Django 4.2.7 on 2023-11-14 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_alter_revista_fimciclo_alter_revista_inciociclo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revista',
            name='revista',
        ),
        migrations.AddField(
            model_name='revista',
            name='linkRevistaAvon',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revista',
            name='linkRevistaCasaEstilo',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revista',
            name='linkRevistaEspaco',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revista',
            name='revistaAvon',
            field=models.FileField(default=1, upload_to='revistas-pdf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revista',
            name='revistaCasaEstilo',
            field=models.FileField(default=1, upload_to='revistas-pdf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revista',
            name='revistaConsultor',
            field=models.FileField(default=1, upload_to='revistas-pdf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revista',
            name='revistaEspaco',
            field=models.FileField(default=1, upload_to='revistas-pdf'),
            preserve_default=False,
        ),
    ]
