# Generated by Django 4.2.7 on 2023-11-14 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_remove_revista_revista_revista_linkrevistaavon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='imagens-combo')),
            ],
        ),
        migrations.CreateModel(
            name='RevistaAvon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo', models.IntegerField()),
                ('incioCiclo', models.DateField()),
                ('fimCiclo', models.DateField()),
                ('revista', models.FileField(upload_to='revistas-pdf')),
                ('imagemRevista', models.ImageField(blank=True, null=True, upload_to='imagens-revistas')),
                ('linkRevista', models.CharField(max_length=255)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.marca')),
            ],
        ),
        migrations.CreateModel(
            name='RevistaCasaEstilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo', models.IntegerField()),
                ('incioCiclo', models.DateField()),
                ('fimCiclo', models.DateField()),
                ('revista', models.FileField(upload_to='revistas-pdf')),
                ('imagemRevista', models.ImageField(blank=True, null=True, upload_to='imagens-revistas')),
                ('linkRevista', models.CharField(max_length=255)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.marca')),
            ],
        ),
        migrations.CreateModel(
            name='RevistaConsultor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo', models.IntegerField()),
                ('incioCiclo', models.DateField()),
                ('fimCiclo', models.DateField()),
                ('revista', models.FileField(upload_to='revistas-pdf')),
                ('imagemRevista', models.ImageField(blank=True, null=True, upload_to='imagens-revistas')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.marca')),
            ],
        ),
        migrations.CreateModel(
            name='RevistaEspaco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo', models.IntegerField()),
                ('incioCiclo', models.DateField()),
                ('fimCiclo', models.DateField()),
                ('revista', models.FileField(upload_to='revistas-pdf')),
                ('imagemRevista', models.ImageField(blank=True, null=True, upload_to='imagens-revistas')),
                ('linkRevista', models.CharField(max_length=255)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.marca')),
            ],
        ),
        migrations.DeleteModel(
            name='Revista',
        ),
    ]
