# Generated by Django 4.2.7 on 2023-11-14 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_banner_revistaavon_revistacasaestilo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='nome',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
