# Generated by Django 4.2.7 on 2023-11-14 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_banner_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='revistaavon',
            name='nomeRef',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revistacasaestilo',
            name='nomeRef',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revistaconsultor',
            name='nomeRef',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revistaespaco',
            name='nomeRef',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
